package com.example.cse225_codes

import android.os.Bundle
import androidx.activity.enableEdgeToEdge
import androidx.appcompat.app.AppCompatActivity
import androidx.core.splashscreen.SplashScreen.Companion.installSplashScreen
import androidx.core.view.ViewCompat
import androidx.core.view.WindowInsetsCompat
import androidx.fragment.app.Fragment
import com.example.cse225_codes.databinding.ActivityExtraBottomNavigationBarWithFragmentsBinding

class ExtraBottomNavigationBarWithFragments : AppCompatActivity() {

    // ActivityExtraBottomNavigationBarWithFragmentsBinding is a class automatically generated by view binder
    // view binding is used to access views in the layout without finding them by their id
    private lateinit var binding: ActivityExtraBottomNavigationBarWithFragmentsBinding

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        installSplashScreen().apply {

        }
        enableEdgeToEdge()
        binding = ActivityExtraBottomNavigationBarWithFragmentsBinding.inflate(layoutInflater)
        setContentView(binding.root)
        replaceFrames(Extra_Bottom_Nav_Home_1())

        binding.bottomNavigationView1.setOnItemSelectedListener {
            when (it.itemId) {
                R.id.bNHome1 -> {
                    replaceFrames(Extra_Bottom_Nav_Home_1())
                    true
                }

                R.id.bNSettings1 -> {
                    replaceFrames(Extra_Bottom_Nav_Settings_1())
                    true
                }

                R.id.bNProfile1 -> {
                    replaceFrames(Extra_Bottom_Nav_Profile_1())
                    true
                }

                else -> false
            }

        }
    }

    fun replaceFrames(fragment: Fragment) {
        val fragmentManger1 = supportFragmentManager
        val fragmentTransaction1 = fragmentManger1.beginTransaction()
        fragmentTransaction1.replace(R.id.fragmentContainerView1, fragment)
        fragmentTransaction1.commit()
    }
}